services:
  postgres:
    container_name: weekly_scheduler
    image: postgres:latest
    ports:
      - "5454:5432"
    volumes:
      - /Users/shnyam/Code/data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
