version: "3.8"
services:
  postgres:
    container_name: weekly_scheduler
    image: postgres:latest
    ports:
      - "5454:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
